dist: trusty
sudo: false
language: cpp

# Add clang later
compiler: 
    - gcc

matrix:
    include:
        os: linux
        addons:
            apt:
                sources:
                    -ubuntu-toolchain-r-test
                packages:
                    - g++-6
        env:
            MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

before_install:
    - eval "${MATRIX_EVAL}"

# Got rid of gtest, using catch2 now to avoid issue with 
# Ubuntu's packaging. 
script:
    - make clean && make all
    - ./bin/test/test_lexer
